version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/java-project"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/kotlin-project"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/groovy-project"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/multi-module-project"
    schedule:
      interval: "weekly"