name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build with Gradle: single-module-project'
        run: cd single-module-project && ./gradlew build && cd ..
      - name: 'Build with Gradle: multi-module-project'
        run: cd multi-module-project && ./gradlew build && cd ..