name: Build

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Skip duplicates and docs
        id: skip
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md", "LICENSE", ".gitignore", ".editorconfig", ".idea/**"]'

      - name: Validate gradle wrapper
        if: steps.skip.outputs.should_skip != 'true'
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        if: steps.skip.outputs.should_skip != 'true'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          cache: gradle
          distribution: temurin

      - name: 'Build with Gradle: java-project'
        if: steps.skip.outputs.should_skip != 'true'
        run: cd java-project && ./gradlew build && cd ..

      - name: 'Build with Gradle: kotlin-project'
        if: steps.skip.outputs.should_skip != 'true'
        run: cd kotlin-project && ./gradlew build && cd ..

      - name: 'Build with Gradle: groovy-project'
        if: steps.skip.outputs.should_skip != 'true'
        run: cd groovy-project && ./gradlew build && cd ..

      - name: 'Build with Gradle: multi-module-project'
        if: steps.skip.outputs.should_skip != 'true'
        run: cd multi-module-project && ./gradlew build && cd ..